"use client";

import { useEffect, useState } from "react";
import { motion } from 'framer-motion';
import "./globals.css";
import Footer from "./components/layout/Footer";
import Navbar from "./components/layout/Navbar";
import Loader from "./components/Loader";
import PageLayout from "./PageLayout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [mounted, setMounted] = useState(false);
  const [showLoader, setShowLoader] = useState(false);
  const [isAppVisible, setIsAppVisible] = useState(false);

  useEffect(() => {
    // setMounted(true)
    // const hasSeenLoader = localStorage.getItem("hasSeenLoader");
    // if (!hasSeenLoader) {
    //   localStorage.setItem("hasSeenLoader", "true");
    //   setShowLoader(true)

    //   setTimeout(() => {
    //     setShowLoader(false)
    //     setIsAppVisible(true);
    //   }, 3400);
    // } else {
    //   setIsAppVisible(true);
    // }

    document.body.classList.add("loading");

    const hasSeenLoader = localStorage.getItem("hasSeenLoader");
    if (!hasSeenLoader) {
      setShowLoader(true);
      localStorage.setItem("hasSeenLoader", "true");
    } else {
      document.body.classList.remove("loading");
      document.body.classList.add("loaded");
    }
  }, []);

  const handleLoaderFinish = () => {
    setShowLoader(false);
    document.body.classList.remove("loading");
    document.body.classList.add("loaded");
  };

  // if(!mounted) null

  return (
    <html lang="en">
      <body className="default">
        {showLoader && <Loader onFinish={handleLoaderFinish} />}

        {/* === Normal layout === */}
        <motion.div
      key="home"
        initial={{ y: isAppVisible ? "100%" : "0%" }}
        animate={{ y: isAppVisible ? "0%" : "0%" }}
        transition={{
          duration: 1.2,
          ease: [0.83, 0, 0.17, 1],
        }}
      // className={styles.homeWrapper}
    >
        <PageLayout>
          {/* <Loader> */}
          <Navbar />
          {children}
          <Footer />
          {/* </Loader> */}
        </PageLayout>
        </motion.div>
      </body>
    </html>
  );
}
