import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/Footer";
import Navbar from "./components/layout/Navbar";
import Loader from "./components/Loader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="default">
        <Loader>
          <Navbar />
          {children}
          <Footer />
        </Loader>
      </body>
    </html>
  );
}
